#! /bin/bash
set -me

SCRIPT_NAME=`basename "$0"`

if [[ -v SOLR_PORT ]] && ! grep -E -q '^[0-9]+$' <<<"${SOLR_PORT:-}"; then
  echo "$SCRIPT_NAME: Setting Solr port to $SOLR_PORT"
  SOLR_PORT=8983
  export SOLR_PORT
fi
