#! /bin/bash
set -me

SCRIPT_NAME=`basename "$0"`
SECRETS_DIR=${SECRETS_DIR:-/secrets}
CONFIG_DIR=${CONFIG_DIR:-/config}

# Get the ApacheSolr core name from ConfigMap if provided.
if [ -s "$CONFIG_DIR/SOLR_APACHESOLR_CORE_NAME" ]; then
  echo "$SCRIPT_NAME: Loading SOLR_APACHESOLR_CORE_NAME from ConfigMap"
  SOLR_APACHESOLR_CORE_NAME="$(<$CONFIG_DIR/SOLR_APACHESOLR_CORE_NAME)"
fi

if [[ -z ${SOLR_APACHESOLR_CORE_NAME+x} ]]; then
    echo "$SCRIPT_NAME: No SOLR_APACHESOLR_CORE_NAME set; skipping core creation."
else
    # Get the Solr Home path from ConfigMap or env.
    if [ -s "$CONFIG_DIR/SOLR_HOME" ]; then
      echo "$SCRIPT_NAME: Loading SOLR_HOME from secrets"
      SOLR_HOME="$(<$CONFIG_DIR/SOLR_HOME)"
    else
      echo "$SCRIPT_NAME: Loading SOLR_HOME from env"
      SOLR_HOME="${SOLR_HOME:-/opt/solr/example/solr}"
    fi

    CORE_DIR="${SOLR_HOME}/${SOLR_APACHESOLR_CORE_NAME}"

    if [[ -d $CORE_DIR ]]; then
        echo "$SCRIPT_NAME: $CORE_DIR exists; skipping core creation"
    else
        echo "$SCRIPT_NAME: Creating drupal/apachesolr core: $SOLR_APACHESOLR_CORE_NAME"

        # Copy the drupal/apachesolr configs over to the Solr core directory.
        mkdir -p -m 775 $CORE_DIR/conf
        mkdir -p -m 775 $CORE_DIR/data
        rsync -a --delete /opt/apachesolr/solr-conf/solr-4.x/ $CORE_DIR/conf

        # Create the core.properties file so Solr can find and init the core on startup.
        touch $CORE_DIR/core.properties
        echo name=$SOLR_APACHESOLR_CORE_NAME > $CORE_DIR/core.properties
        echo transient=false >> $CORE_DIR/core.properties
        echo loadOnStartup=true >> $CORE_DIR/core.properties

        # Start local solr
        start-local-solr

        # See https://github.com/docker-solr/docker-solr/issues/27
        echo "$SCRIPT_NAME: Checking core"
        if ! curl -s 'http://localhost:8983/solr/admin/cores?action=STATUS' | grep -q $SOLR_APACHESOLR_CORE_NAME; then
          echo "Could not find any cores"
          exit 1
        fi

        echo "$SCRIPT_NAME: Created drupal/apachesolr core $SOLR_APACHESOLR_CORE_NAME"

        # check the core_dir exists; otherwise the detecting above will fail after stop/start
        if [ ! -d "$CORE_DIR" ]; then
            echo "$SCRIPT_NAME: Missing $CORE_DIR"
            exit 1
        fi
    fi
fi
