#! /bin/bash
set -me

SCRIPT_NAME=`basename "$0"`

#
# Create Solr cores with a custom schema.
#
# This assumes you are mounting your Schema inside the core directory under
# `$SOLR_HOME/$SOLR_CUSTOM_CORE_NAME/conf`.
#

if [[ -z ${SOLR_CUSTOM_CORE_NAME+x} ]]; then
    echo "$SCRIPT_NAME: No SOLR_CUSTOM_CORE_NAME set; skipping custom core creation."
elif [[ -z ${SOLR_CUSTOM_CORE_CONF_DIF+x} ]]; then
    echo "$SCRIPT_NAME: No SOLR_CUSTOM_CORE_CONF_DIF set; skipping custom core creation."
elif [[ ! -d $SOLR_CUSTOM_CORE_CONF_DIF ]]; then
    echo "$SCRIPT_NAME: Directory SOLR_CUSTOM_CORE_CONF_DIF does not exist. Please mount custom conf there."
else
    SOLR_HOME="${SOLR_HOME:-/opt/solr/example/solr}"
    CORE_DIR="${SOLR_HOME}/${SOLR_CUSTOM_CORE_NAME}"
    CORE_CONFIG="${CORE_DIR}/conf/solrconfig.xml"
    CORE_SCHEMA="${CORE_DIR}/conf/schema.xml"
    CORE_DATA_DIR="${SOLR_HOME}/${SOLR_CUSTOM_CORE_NAME}_data"

    if [[ -d $CORE_DATA_DIR ]]; then
        echo "$SCRIPT_NAME: $CORE_DATA_DIR exists; skipping core creation"
    else

        echo "$SCRIPT_NAME: Creating custom core: $SOLR_CUSTOM_CORE_NAME"

        # Create the core data dir with open permissions.
        mkdir -p -m 775 $CORE_DATA_DIR

        # We do *not* create the conf/index directory, as Solr itself uses that
        # to be sure the core is initialized.

        # Create the core.properties file so Solr can find and init the core on startup.
        REAL_CORE_DIR="${SOLR_HOME}/${SOLR_CUSTOM_CORE_NAME}_core"
        mkdir -p -m 775 $REAL_CORE_DIR
        ln -sfn $SOLR_CUSTOM_CORE_CONF_DIF $REAL_CORE_DIR/conf
        touch $REAL_CORE_DIR/core.properties
        echo name=$SOLR_CUSTOM_CORE_NAME > $REAL_CORE_DIR/core.properties
        echo transient=false >> $REAL_CORE_DIR/core.properties
        echo loadOnStartup=true >> $REAL_CORE_DIR/core.properties

        # Start Solr.
        start-local-solr

        # See https://github.com/docker-solr/docker-solr/issues/27
        echo "$SCRIPT_NAME: Checking core"
        if ! curl -s 'http://localhost:8983/solr/admin/cores?action=STATUS' | grep -q $SOLR_CUSTOM_CORE_NAME; then
          echo "$SCRIPT_NAME: Could not find custom core $SOLR_CUSTOM_CORE_NAME"
          exit 1
        fi

        echo "$SCRIPT_NAME: Created custom core $SOLR_CUSTOM_CORE_NAME"

        # check the CORE_DATA_DIR exists; otherwise the detecting above will fail after stop/start
        if [ ! -d "$CORE_DATA_DIR" ]; then
            echo "$SCRIPT_NAME: Missing $CORE_DATA_DIR"
            exit 1
        fi
    fi
fi
