version: '2'
services:
  web:
    image: ten7/dockstack-php-apache:7.0
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
  db:
    image: ten7/dockstack-mysql
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - /var/lib/mysql
      - ./db-backups:/tmp/db-backups
