version: '2'
services:
  web:
    image: ten7/dockstack-php-apache:5.6
    ports:
      - "80:80"
    env_file:
      - .env
  db:
    image: ten7/dockstack-mysql
    ports:
      - 3306:3306
    env_file:
      - .env
