version: '3'
services:
  web:
    image: ten7/flight-deck-web:5.6
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html:cached
  db:
    image: ten7/flight-deck-db
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - /var/lib/mysql
      - ./db-backups:/tmp/db-backups:cached
  memcached:
    image: memcached:1.4-alpine
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
     - "8001:80"
    env_file:
     - .env
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8002:8025"
  # solr:
  #   image: ten7/flight-deck-solr:5.5
  #   env_file:
  #     - .env
  #   ports:
  #     - "8003:8983"
  # varnish:
  #   image: ten7/flight-deck-varnish:4.0
  #   depends_on:
  #     - web
  #   env_file:
  #     - .env
  #   ports:
  #     - "8004:6081" # HTTP Proxy
  #     - "8005:6082" # Control terminal
  #
  ## Webgrind lets you example XDebug profiling files without kcachegrind.
  #
  # webgrind:
  #   image: clue/webgrind
  #   ports:
  #     - "8006:80"
  #   volumes:
  #     - ./src:/tmp
