#! /bin/bash
set -me

SCRIPT_NAME=`basename "$0"`

SECRETS_DIR=${SECRETS_DIR:-/secrets}
CONFIG_DIR=${CONFIG_DIR:-/config}

# Get the Varnish backend hostname from ConfigMap or env.
if [ -s "$CONFIG_DIR/VARNISH_BACKEND_HOST" ]; then
  echo "$SCRIPT_NAME: Loading VARNISH_BACKEND_HOST from ConfigMap"
  VARNISH_BACKEND_HOST="$(<$CONFIG_DIR/VARNISH_BACKEND_HOST)"
else
  echo "$SCRIPT_NAME: Loading VARNISH_BACKEND_HOST from env"
  VARNISH_BACKEND_HOST=${VARNISH_BACKEND_HOST:-web}
fi

# Set the Varnish backend hostname.
echo "$SCRIPT_NAME: Setting Varnish backend host to $VARNISH_BACKEND_HOST"
sed -i 's/VARNISH_BACKEND_HOST/'"${VARNISH_BACKEND_HOST}"'/' /etc/varnish/backend.vcl

# Get the Varnish backend port number from ConfigMap or env.
if [ -s "$CONFIG_DIR/VARNISH_BACKEND_PORT" ]; then
  echo "$SCRIPT_NAME: Loading VARNISH_BACKEND_PORT from ConfigMap"
  VARNISH_BACKEND_PORT="$(<$CONFIG_DIR/VARNISH_BACKEND_PORT)"
else
  echo "$SCRIPT_NAME: Loading VARNISH_BACKEND_PORT from env"
  VARNISH_BACKEND_PORT=${VARNISH_BACKEND_PORT:-80}
fi

# Set the Varnish backend port.
echo "$SCRIPT_NAME: Setting Varnish backend port to $VARNISH_BACKEND_PORT"
sed -i 's/VARNISH_BACKEND_PORT/'"${VARNISH_BACKEND_PORT}"'/' /etc/varnish/backend.vcl
