#! /bin/bash
set -me

SCRIPT_NAME=`basename "$0"`

VARNISH_SECRET=${VARNISH_SECRET:-secret}

if [ -n "$VARNISH_SECRET" ]; then
  echo "$SCRIPT_NAME: Setting Varnish secret to $VARNISH_SECRET"
  sed -i 's/VARNISH_SECRET/'"${VARNISH_SECRET}"'/' /etc/varnish/secret
fi
