#! /bin/bash
set -me

SCRIPT_NAME=`basename "$0"`

PHP_XDEBUG_INI_PATH="${PHP_XDEBUG_INI_PATH:-/etc/php7/conf.d/xdebug.ini}"

PHP_XDEBUG_ENABLED="${PHP_XDEBUG_ENABLED:-0}"
PHP_XDEBUG_AUTOSTART="${PHP_XDEBUG_AUTOSTART:-0}"
PHP_XDEBUG_REMOTE_CONNECT_BACK="${PHP_XDEBUG_REMOTE_CONNECT_BACK:-0}"
PHP_XDEBUG_STDOUT_LOGS="${PHP_XDEBUG_STDOUT_LOGS:-0}"

if [ "$PHP_XDEBUG_ENABLED" -eq "1" ]; then
  echo "$SCRIPT_NAME: Enabling XDebug..."
  sed -i 's/^;zend_extension.*/zend_extension = xdebug.so/' $PHP_XDEBUG_INI_PATH

  echo "$SCRIPT_NAME: Updating XDebug config file: $PHP_XDEBUG_INI_PATH"

  if [ "$PHP_XDEBUG_AUTOSTART" -eq "0" ]; then
    echo "$SCRIPT_NAME: Disabling XDebug autostart."
    sed -i 's/^xdebug.remote_autostart.*/xdebug.remote_autostart = 0/' $PHP_XDEBUG_INI_PATH
  fi

  if [ "$PHP_XDEBUG_REMOTE_CONNECT_BACK" -eq "0" ]; then
    echo "$SCRIPT_NAME: Disabling XDebug remote connect back."
    sed -i 's/^xdebug.remote_connect_back.*/xdebug.remote_connect_back = 0/' $PHP_XDEBUG_INI_PATH
  fi

  if [ -n "$PHP_XDEBUG_REMOTE_HOST" ]; then
    echo "$SCRIPT_NAME: Setting XDebug remote host to $PHP_XDEBUG_REMOTE_HOST"
    sed -i 's/^xdebug.remote_host.*/'"xdebug.remote_host = ${PHP_XDEBUG_REMOTE_HOST}"'/' $PHP_XDEBUG_INI_PATH
  fi

  if [ "$PHP_XDEBUG_STDOUT_LOGS" -eq "1" ]; then
    echo "$SCRIPT_NAME: Forwarding XDebug logs to STDOUT."
    ln -sfn /dev/stdout /var/log/apache2/xdebug.log
  fi

fi
