#! /bin/bash
set -me

SCRIPT_NAME=`basename "$0"`

PHP_XDEBUG_INI_PATH="${PHP_XDEBUG_INI_PATH:-/etc/php7/conf.d/xdebug.ini}"

PHP_XDEBUG_ENABLED="${PHP_XDEBUG_ENABLED:-0}"
PHP_XDEBUG_PROFILE_FORCE="${PHP_XDEBUG_PROFILE_FORCE:-0}"

if [ "$PHP_XDEBUG_ENABLED" -eq "1" ]; then
  echo "$SCRIPT_NAME: Updating XDebug config file for profiling: $PHP_XDEBUG_INI_PATH"
  
  if [ -n "$PHP_XDEBUG_PROFILE_TRIGGER" ]; then
    echo "$SCRIPT_NAME: Setting XDebug profile trigger to $PHP_XDEBUG_PROFILE_TRIGGER."
    sed -i 's/^xdebug.profiler_enable_trigger_value =.*/'"xdebug.profiler_enable_trigger_value = ${PHP_XDEBUG_PROFILE_TRIGGER}"'/' /etc/php7/conf.d/xdebug.ini
  fi

  if [ "$PHP_XDEBUG_PROFILE_FORCE" -eq "1" ]; then
    echo "$SCRIPT_NAME: Forcing XDebug profiling to always run!"
    sed -i 's/^xdebug.profiler_enable =.*/xdebug.profiler_enable = 1/' $PHP_XDEBUG_INI_PATH
  fi

fi
