#! /bin/bash
set -me

SCRIPT_NAME=`basename "$0"`

# Allow the Apache docroot to be overridden.
APACHE_DOCROOT_DIR="${APACHE_DOCROOT_DIR:-/var/www/html}"
if [ -n "$APACHE_DOCROOT_DIR" ]; then
  echo "$SCRIPT_NAME: Setting APACHE_DOCROOT_DIR to $APACHE_DOCROOT_DIR"
  sed -i 's@^\s*<Directory.*@'"   <Directory \"${APACHE_DOCROOT_DIR}\">"'@' /etc/apache2/sites.d/000_default.conf
fi

# Allow the site name to be overriden.
APACHE_SITE_NAME="${APACHE_SITE_NAME:-docker.test}"
if [ -n "$APACHE_SITE_NAME" ]; then
  echo "$SCRIPT_NAME: Setting APACHE_SITE_NAME to $APACHE_SITE_NAME"
  sed -i 's@^\s*ServerName.*@'"  ServerName ${APACHE_SITE_NAME}"'@'  /etc/apache2/sites.d/000_default.conf
fi

# Allow for site aliases to be provided.
APACHE_SITE_ALIAS="${APACHE_SITE_ALIAS:-docker.localhost}"
if [ -n "$APACHE_SITE_ALIAS" ]; then
  echo "$SCRIPT_NAME: Setting APACHE_SITE_ALIAS to $APACHE_SITE_ALIAS"
  sed -i 's@^\s*ServerAlias.*@'"  ServerAlias ${APACHE_SITE_ALIAS}"'@'  /etc/apache2/sites.d/000_default.conf
fi
