#! /bin/bash
set -me

SCRIPT_NAME=`basename "$0"`

# Perform a one-time MySQL initialization if necessary.
if [ ! -d "/var/lib/mysql/mysql" ]; then
  echo "$SCRIPT_NAME: Initializing MySQL."
  mysql_install_db --user=mysql --datadir=/var/lib/mysql > /dev/null

  # Start MySQL in the background if it isn't already.
  mysql-background-start.sh

  # Drop the default 'test' database.
  echo "$SCRIPT_NAME: Dropping the default 'test' database."
  mysqladmin -f drop test > /dev/null
fi
