#! /bin/bash
set -me

SCRIPT_NAME=`basename "$0"`

SECRETS_DIR=${SECRETS_DIR:-/secrets}
CONFIG_DIR=${CONFIG_DIR:-/config}

# Get the Varnish secret from ConfigMap or env.
if [ -s "$CONFIG_DIR/VARNISH_SECRET" ]; then
  echo "$SCRIPT_NAME: Loading VARNISH_SECRET from secrets"
  VARNISH_SECRET="$(<$SECRETS_DIR/VARNISH_SECRET)"
else
  echo "$SCRIPT_NAME: Loading VARNISH_SECRET from env"
  VARNISH_SECRET=${VARNISH_SECRET:-secret}
fi

# Set the Varnish secret.
echo "$SCRIPT_NAME: Setting Varnish secret"
sed -i 's/VARNISH_SECRET/'"${VARNISH_SECRET}"'/' /etc/varnish/secret
