#! /bin/bash
set -me

SCRIPT_NAME=`basename "$0"`
SECRETS_DIR=${SECRETS_DIR:-/secrets}
CONFIG_DIR=${CONFIG_DIR:-/config}

# Get the site environment path from ConfigMap or env.
if [ -s "$CONFIG_DIR/T7_SITE_ENVIRONMENT" ]; then
  echo "$SCRIPT_NAME: Loading T7_SITE_ENVIRONMENT from ConfigMap"
  T7_SITE_ENVIRONMENT="$(<$CONFIG_DIR/T7_SITE_ENVIRONMENT)"
else
  echo "$SCRIPT_NAME: Loading T7_SITE_ENVIRONMENT from env"
  T7_SITE_ENVIRONMENT="${T7_SITE_ENVIRONMENT:-docker-dev}"
fi

# Set the Apache docroot path.
echo "$SCRIPT_NAME: Setting T7_SITE_ENVIRONMENT to $T7_SITE_ENVIRONMENT"

sed -i 's@^\s*T7_SITE_ENVIRONMENT.*@'"T7_SITE_ENVIRONMENT=\"${T7_SITE_ENVIRONMENT}\""'@' /var/www/.bashrc
