#! /bin/bash
set -me

SCRIPT_NAME=`basename "$0"`
SECRETS_DIR=${SECRETS_DIR:-/secrets}
CONFIG_DIR=${CONFIG_DIR:-/config}

# Get the Apache docroot path from ConfigMap or env.
if [ -s "$CONFIG_DIR/APACHE_DOCROOT_DIR" ]; then
  echo "$SCRIPT_NAME: Loading APACHE_DOCROOT_DIR from ConfigMap"
  APACHE_DOCROOT_DIR="$(<$CONFIG_DIR/APACHE_DOCROOT_DIR)"
else
  echo "$SCRIPT_NAME: Loading APACHE_DOCROOT_DIR from env"
  APACHE_DOCROOT_DIR="${APACHE_DOCROOT_DIR:-/var/www/html}"
fi

# Set the Apache docroot path.
echo "$SCRIPT_NAME: Setting APACHE_DOCROOT_DIR to $APACHE_DOCROOT_DIR"
sed -i 's@^\s*<Directory.*@'"   <Directory \"${APACHE_DOCROOT_DIR}\">"'@' /etc/apache2/sites.d/000_default.conf
sed -i 's@^\s*DocumentRoot.*@'"   DocumentRoot ${APACHE_DOCROOT_DIR}"'@' /etc/apache2/sites.d/000_default.conf

# Get the Apache server name from ConfigMap or env.
if [ -s "$CONFIG_DIR/APACHE_SITE_NAME" ]; then
  echo "$SCRIPT_NAME: Loading APACHE_SITE_NAME from ConfigMap"
  APACHE_SITE_NAME="$(<$CONFIG_DIR/APACHE_SITE_NAME)"
else
  echo "$SCRIPT_NAME: Loading APACHE_SITE_NAME from env"
  APACHE_SITE_NAME="${APACHE_SITE_NAME:-docker.test}"
fi

# Set the Apache server name.
echo "$SCRIPT_NAME: Setting APACHE_SITE_NAME to $APACHE_SITE_NAME"
sed -i 's@^\s*ServerName.*@'"  ServerName ${APACHE_SITE_NAME}"'@'  /etc/apache2/sites.d/000_default.conf


# Get the Apache server alias from ConfigMap or env.
if [ -s "$CONFIG_DIR/APACHE_SITE_ALIAS" ]; then
  echo "$SCRIPT_NAME: Loading APACHE_SITE_ALIAS from ConfigMap"
  APACHE_SITE_ALIAS="$(<$CONFIG_DIR/APACHE_SITE_ALIAS)"
else
  echo "$SCRIPT_NAME: Loading APACHE_SITE_ALIAS from env"
  APACHE_SITE_ALIAS="${APACHE_SITE_ALIAS:-docker.localhost}"
fi

# Set the Apache server alias.
echo "$SCRIPT_NAME: Setting APACHE_SITE_ALIAS to $APACHE_SITE_ALIAS"
sed -i 's@^\s*ServerAlias.*@'"  ServerAlias ${APACHE_SITE_ALIAS}"'@'  /etc/apache2/sites.d/000_default.conf
