#! /bin/bash
set -me

SCRIPT_NAME=`basename "$0"`
SECRETS_DIR=${SECRETS_DIR:-/secrets}
CONFIG_DIR=${CONFIG_DIR:-/config}

# Get the HTTPS keys from secrets.
if [ -s "$SECRETS_DIR/HTTPS_CERT" ]; then
  echo "$SCRIPT_NAME: Loading HTTPS_CERT from secrets"
  
  if [ -s "$SECRETS_DIR/HTTPS_KEY" ]; then
    echo "$SCRIPT_NAME: Loading HTTPS_KEY from secrets"
  
    # Remove existing keys.
    rm -f /etc/ssl/apache2/custom.pem
    rm -f /etc/ssl/apache2/custom.key

    cp "$SECRETS_DIR/HTTPS_CERT" /etc/ssl/apache2/custom.pem
    cp "$SECRETS_DIR/HTTPS_KEY" /etc/ssl/apache2/custom.key

    cat /etc/ssl/apache2/custom.pem
    cat /etc/ssl/apache2/custom.key


    # Set the appropriate permissions
    chmod u=rw,g=,o= /etc/ssl/apache2/custom.pem
    chmod u=rw,g=,o= /etc/ssl/apache2/custom.key

    # Update the vhost config.
    sed -i 's@^\s*SSLCertificateFile.*@'"  SetEnv SSLCertificateFile /etc/ssl/apache2/custom.pem"'@' /etc/apache2/sites.d/000_default.conf
    sed -i 's@^\s*SSLCertificateKeyFile.*@'"  SetEnv SSLCertificateKeyFile /etc/ssl/apache2/custom.key"'@' /etc/apache2/sites.d/000_default.conf
    
  else
    echo "$SCRIPT_NAME: Missing HTTPS_KEY from secrets."
  fi
fi
