#! /bin/bash
set -me

SCRIPT_NAME=`basename "$0"`
SECRETS_DIR=${SECRETS_DIR:-/secrets}
CONFIG_DIR=${CONFIG_DIR:-/config}

# Get the PHP INI file path from ConfigMap or env.
if [ -s "$CONFIG_DIR/PHP_INI_PATH" ]; then
  echo "$SCRIPT_NAME: Loading PHP_INI_PATH from ConfigMap"
  PHP_INI_PATH="$(<$CONFIG_DIR/PHP_INI_PATH)"
else
  echo "$SCRIPT_NAME: Loading PHP_INI_PATH from env"
  PHP_INI_PATH="${PHP_INI_PATH:-/etc/php7/php.ini}"
fi

# Get the PHP sendmail path from ConfigMap if present.
if [ -s "$CONFIG_DIR/PHP_SENDMAIL_PATH" ]; then
  echo "$SCRIPT_NAME: Loading PHP sendmail_path from ConfigMap"
  PHP_SENDMAIL_PATH="$(<$CONFIG_DIR/PHP_SENDMAIL_PATH)"
fi

if [ -n "$PHP_SENDMAIL_PATH" ]; then
  echo "$SCRIPT_NAME: Setting sendmail_path to $PHP_SENDMAIL_PATH."
  sed -i 's@^;sendmail_path.*@'"sendmail_path = ${PHP_SENDMAIL_PATH}"'@' $PHP_INI_PATH
fi
