#! /bin/bash
set -me

SCRIPT_NAME=`basename "$0"`
SECRETS_DIR=${SECRETS_DIR:-/secrets}
CONFIG_DIR=${CONFIG_DIR:-/config}

# Get the PHP INI file path from ConfigMap or env.
if [ -s "$CONFIG_DIR/PHP_INI_PATH" ]; then
  echo "$SCRIPT_NAME: Loading PHP_INI_PATH from ConfigMap"
  PHP_INI_PATH="$(<$CONFIG_DIR/PHP_INI_PATH)"
else
  echo "$SCRIPT_NAME: Loading PHP_INI_PATH from env"
  PHP_INI_PATH="${PHP_INI_PATH:-/etc/php7/php.ini}"
fi

# Get the PHP sendmail path from ConfigMap if present.
if [ -s "$CONFIG_DIR/PHP_SENDMAIL_PATH" ]; then
  echo "$SCRIPT_NAME: Loading PHP sendmail_path from ConfigMap"
  PHP_SENDMAIL_PATH="$(<$CONFIG_DIR/PHP_SENDMAIL_PATH)"
fi

if [ -n "$PHP_SENDMAIL_PATH" ]; then
  echo "$SCRIPT_NAME: Setting sendmail_path to $PHP_SENDMAIL_PATH."
  sed -i 's@^;sendmail_path.*@'"sendmail_path = ${PHP_SENDMAIL_PATH}"'@' $PHP_INI_PATH
fi

# Get the PHP max_execution_time from ConfigMap if present.
if [ -s "$CONFIG_DIR/PHP_MAX_EXEC_TIME" ]; then
  echo "$SCRIPT_NAME: Loading PHP max_execution_time from ConfigMap"
  PHP_MAX_EXEC_TIME="$(<$CONFIG_DIR/PHP_MAX_EXEC_TIME)"
else
  echo "$SCRIPT_NAME: Loading PHP max_execution_time from env"
  PHP_MAX_EXEC_TIME="${PHP_MAX_EXEC_TIME:-120}"
fi

if [ -n "$PHP_MAX_EXEC_TIME" ]; then
  echo "$SCRIPT_NAME: Setting max_execution_time to $PHP_MAX_EXEC_TIME."
  sed -i 's@^max_execution_time.*@'"max_execution_time = ${PHP_MAX_EXEC_TIME}"'@' $PHP_INI_PATH
fi

# Get the PHP max_input_vars from ConfigMap if present.
if [ -s "$CONFIG_DIR/PHP_MAX_INPUT_VARS" ]; then
  echo "$SCRIPT_NAME: Loading PHP max_input_vars from ConfigMap"
  PHP_MAX_INPUT_VARS="$(<$CONFIG_DIR/PHP_MAX_INPUT_VARS)"
else
  echo "$SCRIPT_NAME: Loading PHP max_input_vars from env"
  PHP_MAX_INPUT_VARS="${PHP_MAX_INPUT_VARS:-3000}"
fi

if [ -n "$PHP_MAX_INPUT_VARS" ]; then
  echo "$SCRIPT_NAME: Setting max_input_vars to $PHP_MAX_INPUT_VARS."
  sed -i 's@^;\s*max_input_vars.*@'"max_input_vars = ${PHP_MAX_INPUT_VARS}"'@' $PHP_INI_PATH
fi

# Get the PHP memory_limit from ConfigMap if present.
if [ -s "$CONFIG_DIR/PHP_MEMORY_LIMIT" ]; then
  echo "$SCRIPT_NAME: Loading PHP memory_limit from ConfigMap"
  PHP_MEMORY_LIMIT="$(<$CONFIG_DIR/PHP_MEMORY_LIMIT)"
else
  echo "$SCRIPT_NAME: Loading PHP memory_limit from env"
  PHP_MEMORY_LIMIT="${PHP_MEMORY_LIMIT:-320M}"
fi

if [ -n "$PHP_MEMORY_LIMIT" ]; then
  echo "$SCRIPT_NAME: Setting memory_limit to $PHP_MEMORY_LIMIT."
  sed -i 's@^;\s*memory_limit.*@'"memory_limit = ${PHP_MEMORY_LIMIT}"'@' $PHP_INI_PATH
fi
