version: '3'
services:
  web:
    build: apache/7.0
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ../.env
  db:
    build: db
    ports:
      - 3306:3306
    env_file:
      - .env
  memcached:
    image: memcached:1.5-alpine
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
     - "8001:80"
    env_file:
     - .env
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8002:8025"
  solr:
    build: solr/5.5
    env_file:
      - .env
    ports:
      - "8003:8983"
  varnish:
    build: varnish/4.1
    depends_on:
      - web
    env_file:
      - .env
    ports:
      - "8004:6081" # HTTP Proxy
      - "8005:6082" # Control terminal
