#! /bin/bash
set -me

SCRIPT_NAME=`basename "$0"`

# Create the run directory, if necessary.
mkdir -p -m 777 /var/run/mysqld/

# Perform a one-time MySQL initialization if necessary.
if [ ! -d "/var/lib/mysql/mysql" ]; then
  echo "$SCRIPT_NAME: Initializing MySQL."
  mysql_install_db --user=mysql > /dev/null
fi
