#! /bin/bash
set -me

SCRIPT_NAME=`basename "$0"`

if [ -n "$MYSQL_ROOT_PASSWORD" ]; then
  # Create a tempfile for our startup script.
  SQL_INIT_FILE=$(mktemp)

  # Change the owner of the tempfile so MySQL can read it.
  chown mysql:mysql $SQL_INIT_FILE

  # Create a root user with remote-login capability.
  echo "GRANT ALL ON *.* TO 'root'@'%' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';" >> $SQL_INIT_FILE

  # Start MySQL in the background if it isn't already.
  mysql-background-start.sh

  echo "$SCRIPT_NAME: Creating remote root user."
  mysql < $SQL_INIT_FILE

else
  echo "$SCRIPT_NAME: Skipping remote root user creation."

fi
