#! /bin/bash
set -me

SCRIPT_NAME=`basename "$0"`
SECRETS_DIR=${SECRETS_DIR:-/secrets}
CONFIG_DIR=${CONFIG_DIR:-/config}

# Get the user remote hostnames from secrets, if provided.
if [ -s "$SECRETS_DIR/MYSQL_USER_REMOTE_HOSTNAMES" ]; then
  echo "$SCRIPT_NAME: Loading MYSQL_USER_REMOTE_HOSTNAMES from secrets"
  MYSQL_USER_REMOTE_HOSTNAMES="$(<$SECRETS_DIR/MYSQL_USER_REMOTE_HOSTNAMES)"
else
  echo "$SCRIPT_NAME: Loading MYSQL_USER_REMOTE_HOSTNAMES from env"
  MYSQL_USER_REMOTE_HOSTNAMES=${MYSQL_USER_REMOTE_HOSTNAMES:-%}
fi

# Get the Additional Databases from secrets, if provided.
if [ -s "$SECRETS_DIR/ADDITIONAL_DATABASES" ]; then
  echo "$SCRIPT_NAME: Loading ADDITIONAL_DATABASES from secrets"
  ADDITIONAL_DATABASES="$(<$SECRETS_DIR/ADDITIONAL_DATABASES)"
fi

if [ -n "$ADDITIONAL_DATABASES" ]; then

  # Filter out localhost and loopback from MYSQL_USER_REMOTE_HOSTNAMES.
  MYSQL_USER_REMOTE_HOSTNAMES=${MYSQL_USER_REMOTE_HOSTNAMES//localhost/}
  MYSQL_USER_REMOTE_HOSTNAMES=${MYSQL_USER_REMOTE_HOSTNAMES//127\.0\.0\.1/}

  # Create a tempfile for our startup script.
  SQL_INIT_FILE=$(mktemp)

  # Change the owner of the tempfile so MySQL can read it.
  chown mysql:mysql $SQL_INIT_FILE

  for ADD_DB_NAME in $ADDITIONAL_DATABASES; do
    echo "CREATE DATABASE IF NOT EXISTS $ADD_DB_NAME;" >> $SQL_INIT_FILE

    # Add grants for all remote hostnames.
    for MYSQL_USER_REMOTE_HOSTNAME in $MYSQL_USER_REMOTE_HOSTNAMES; do
      echo "GRANT ALL ON $ADD_DB_NAME.* TO '$MYSQL_USER'@'$MYSQL_USER_REMOTE_HOSTNAME' ;" >> $SQL_INIT_FILE
    done;
  done;

  echo "FLUSH PRIVILEGES;" >> $SQL_INIT_FILE

  # Start MySQL in the background if it isn't already.
  mysql-background-start.sh

  # Run the script file.
  echo "$SCRIPT_NAME: Initializing additional databases."
  mysql < $SQL_INIT_FILE

else
  echo "$SCRIPT_NAME: No additional databases specified."
fi
