#! /bin/bash

SCRIPT_NAME=`basename "$0"`
SECRETS_DIR=${SECRETS_DIR:-/secrets}
CONFIG_DIR=${CONFIG_DIR:-/config}

# Get the Max Allowed Packet size from ConfigMap, if provided.
if [ -s "$CONFIG_DIR/MYSQL_MAX_ALLOWED_PACKET" ]; then
  echo "$SCRIPT_NAME: Loading MYSQL_MAX_ALLOWED_PACKET from ConfigMap"
  MYSQL_MAX_ALLOWED_PACKET="$(<$CONFIG_DIR/MYSQL_MAX_ALLOWED_PACKET)"
fi

# Change the Max Allowed Packet size, if set.
if [ -n "$MYSQL_MAX_ALLOWED_PACKET" ]; then
    echo "$SCRIPT_NAME: Setting max_allowed_packet to $MYSQL_MAX_ALLOWED_PACKET"
    sed -i 's/^max_allowed_packet.*/'"max_allowed_packet = ${MYSQL_MAX_ALLOWED_PACKET}"'/' /etc/mysql/my.cnf
fi

# Get the max query size from ConfigMap, if provided.
if [ -s "$CONFIG_DIR/MYSQL_QUERY_CACHE_SIZE" ]; then
  echo "$SCRIPT_NAME: Loading MYSQL_QUERY_CACHE_SIZE from ConfigMap"
  MYSQL_QUERY_CACHE_SIZE="$(<$CONFIG_DIR/MYSQL_QUERY_CACHE_SIZE)"
fi

# Set the max query cache size.
if [ -n "$MYSQL_QUERY_CACHE_SIZE" ]; then
  echo "$SCRIPT_NAME: Setting query_cache_size to $MYSQL_QUERY_CACHE_SIZE"
  sed -i 's/^query_cache_size.*/'"query_cache_size = ${MYSQL_QUERY_CACHE_SIZE}"'/' /etc/mysql/my.cnf
fi
