#! /bin/bash

SCRIPT_NAME=`basename "$0"`

if [ ! -z "$MYSQL_RANDOM_ROOT_PASSWORD" ]; then
  export MYSQL_ROOT_PASSWORD=`pwgen -1 32`
	echo "$SCRIPT_NAME: Generated root password: $MYSQL_ROOT_PASSWORD"
fi

if [ -n "$MYSQL_ROOT_PASSWORD" ]; then
  echo "$SCRIPT_NAME: Setting MySQL root password."
  mysql-background-start.sh
  mysqladmin -u root password $MYSQL_ROOT_PASSWORD
  sed -i 's@^\s*password=.*@'"password=${MYSQL_ROOT_PASSWORD}"'@'  /root/.my.cnf
fi
