#! /bin/bash

SCRIPT_NAME=`basename "$0"`

if [ ! -z "$MYSQL_RANDOM_ROOT_PASSWORD" ]; then
  export MYSQL_ROOT_PASSWORD=`pwgen -1 32`
	echo "$SCRIPT_NAME: Generated root password: $MYSQL_ROOT_PASSWORD"
fi

if [ -n "$MYSQL_ROOT_PASSWORD" ]; then
  echo "$SCRIPT_NAME: Setting MySQL root password."
  mysql-background-start.sh
  mysql -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('$MYSQL_ROOT_PASSWORD')";
fi
