#! /bin/bash
set -me

SCRIPT_NAME=`basename "$0"`

if [[ -z ${SOLR_APACHESOLR_CORE_NAME+x} ]]; then
    echo "$SCRIPT_NAME: No SOLR_APACHESOLR_CORE_NAME set; skipping core creation."
else
    CORE_DIR="${SOLR_HOME:-/opt/solr/server/solr}/$SOLR_APACHESOLR_CORE_NAME"

    if [[ -d $CORE_DIR ]]; then
        echo "$SCRIPT_NAME: $CORE_DIR exists; skipping drupal/apachesolr core creation"
    else
        echo "$SCRIPT_NAME: Creating drupal/apachesolr core: $SOLR_APACHESOLR_CORE_NAME"

        # Copy the drupal/apachesolr configs over to the Solr core directory.
        mkdir -p -m 775 $CORE_DIR/conf
        mkdir -p -m 775 $CORE_DIR/data
        rsync -a --delete /opt/apachesolr/solr-conf/solr-5.x/ $CORE_DIR/conf

        # # Create the core.properties file so Solr can find and init the core on startup.
        # touch $CORE_DIR/core.properties
        # echo name=$SOLR_APACHESOLR_CORE_NAME > $CORE_DIR/core.properties
        # echo transient=false >> $CORE_DIR/core.properties
        # echo loadOnStartup=true >> $CORE_DIR/core.properties

        # Create the core.
        /opt/solr/bin/solr create -c $SOLR_APACHESOLR_CORE_NAME

        # See https://github.com/docker-solr/docker-solr/issues/27
        echo "$SCRIPT_NAME: Checking core"
        if ! curl -s 'http://localhost:8983/solr/admin/cores?action=STATUS' | grep -q $SOLR_APACHESOLR_CORE_NAME; then
          echo "Could not find any cores"
          exit 1
        fi

        echo "$SCRIPT_NAME: Created drupal/apachesolr core $SOLR_APACHESOLR_CORE_NAME"

        # check the core_dir exists; otherwise the detecting above will fail after stop/start
        if [ ! -d "$CORE_DIR" ]; then
            echo "$SCRIPT_NAME: Missing $CORE_DIR"
            exit 1
        fi
    fi
fi
